Repository LINCnil/pia, pull requests merged in 2018-11, with the labels that each got.

#284 Create hr.json
  src/assets/i18n/hr.json
Labels: Status: In Progress, Type: Content, Type: Enhancement

#289 latest translations
  src/assets/i18n/el.json
Labels: Type: Content

#300 Added Croatian, Danish and Lithuanian to the frontend
  package.json
  src/app/authentication/authentication.component.html
  src/app/header/header.component.html
  src/app/services/languages.service.ts
  src/assets/i18n/cz.json
  src/assets/i18n/de.json
  src/assets/i18n/dk.json
  src/assets/i18n/el.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
  src/assets/i18n/fi.json
  src/assets/i18n/fr.json
  src/assets/i18n/hr.json
  src/assets/i18n/hu.json
  src/assets/i18n/it.json
  src/assets/i18n/lt.json
  src/assets/i18n/nl.json
  src/assets/i18n/no.json
  src/assets/i18n/pl.json
  src/assets/i18n/pt.json
  src/assets/i18n/ro.json
  yarn.lock
Labels: Type: Content, Type: Enhancement
